export const FETCH_ALL_CHATROOM = "FETCH_ALL_CHATROOM";
export const FETCH_CHATROOM_BY_ID = "FETCH_CHATROOM_BY_ID";
// export const GET_CHATROOM_BY_ID = "GET_CHATROOM_BY_ID";
// export const DELETE_CHATRROM = "DELETE_CHATRROM";

